import ShoppingCartButton from '@/components/cartBtn/cartBtn'
import Header from '@/components/header/header'
import { Providers } from '@/components/providersReduxToolkit/providersReduxToolkit'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Routing test App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<Providers>
				<body className={inter.className}>
					<Header>
						<ShoppingCartButton />
					</Header>
					<main className={'main'}>{children}</main>
				</body>
			</Providers>
		</html>
	)
}
